plugins:
  kolide_enabled:
    default: false
    client: true
  kolide_api_key:
    default: ''
    secret: true
  kolide_webhook_secret:
    default: ''
    secret: true
  kolide_verbose_log:
    default: false
  kolide_onboarding_topic_id:
    default: 0
    client: true
